
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title>Painter SVG</title>
    <meta name="description" content="Module JS1 - Exercice Icons">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
    <link href="./css/lib/normalize.css" rel="stylesheet">
    <link href="./css/lib/layout.css" rel="stylesheet">
    <link href="./css/lib/theme.css" rel="stylesheet">
    
  </head>
  <body>
    <header class="banner">
      <a class="banner-link" href="./">
        <strong class="banner-title">Painter SVG</strong>
        <small>Avec PHP et en POO !</small>
      </a>
    </header>

    <main class="project container">

    <svg width="1024" height="768" version="1.1" xmlns="http://www.w3.org/2000/svg">

      <!-- <rect x="10" y="10" width="30" height="30" stroke="black" fill="transparent" stroke-width="5"/>
      <rect x="20" y="20" width="40" height="60" stroke="black" fill="transparent" stroke-width="5"/>
      <rect x="60" y="10" rx="10" ry="10" width="30" height="30" stroke="black" fill="transparent" stroke-width="5"/>

      <circle cx="25" cy="75" r="20" stroke="red" fill="transparent" stroke-width="5"/>
      <ellipse cx="75" cy="75" rx="20" ry="5" stroke="red" fill="transparent" stroke-width="5"/>
      <polygon points="50 160 55 180 70 180 60 190 65 205 50 195 35 205 40 190 30 180 45 180"
      stroke="yellow" fill="transparent" stroke-width="5"/>
      <path d="M20,230 Q40,205 50,230 T90,230" fill="none" stroke="blue" stroke-width="5"/>
      <polygon points="250,60 100,400 400,400" width="30" height="30" stroke="grey" fill="pink" stroke-width="5" /> -->

      <?php echo $svg ?>;
      <?php echo $svg2 ?>;
      <?php echo $svg3 ?>;
      <?php echo $svg4 ?>;
      <?php echo $svg5 ?>;


      


    </svg>
     

     
    </main>

    <footer id="mentions" class="mentions">
      <p><strong> &copy; Olivier Meunier - Tous&nbsp;droits&nbsp;réservés</strong>
    </footer>

    <!-- Affichage du support -->
    <script src=".resources/js/resources.js" data-md=".resources/statement.md"></script>

  </body>
</html>
